apiVersion: v1
kind: Service
metadata:
  name:  nginx-nodeport
spec:
  type: nodeport
  selector: 
    project: expense
    module: backend
    environment: dev
  ports: 
    - name: nginx-service-port
      protocol: TCP
      port: 80
      targetPort: 80